# Generated by Django 4.2.9 on 2024-01-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cartitems", "0001_initial"),
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("SUBMITTED", "Submitted")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "cartitems",
                    models.ManyToManyField(through="cartitems.CartItem", to="products.product"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
            options={"db_table": "cart"},
        )
    ]
